### ISSUE TITLE
Small Bug in Predict

### ISSUE THREAD

**Issue by crforsythe** [arteagac/xlogit#11]
Hi Cristian, 

Hope you're well! Just wanted to let you know that there is a small bug in the predict method. For the multinomial login class on line 283-284, it reads as follows:

` if weights is not None:  # Reshape weights to match input data
      weights = weights[y.ravel().astype(bool)]`

but it should read as follows to prevent operation on None y values:
`        if weights is not None and not predict_mode:  # Reshape weights to match input data
            weights = weights[y.ravel().astype(bool)]`

**Comment by arteagac** [comment]
Hi @crforsythe. Thanks a lot for reporting this bug. I think I need to remove the dependency on `y` to extract the unique weights. The way it is coded right now implies that weights can not be used in prediction (when there is no `y`). Perhaps it works best to simply take the weights for the first alternative in the long format, as weights are repeated across alternatives (See illustration below). I think this will work but would like to hear your opinion on this. 

![image](https://user-images.githubusercontent.com/13966395/194720419-96cb1991-d4d6-4408-8134-659adaef9aad.png)

**Comment by crforsythe** [comment]
Please - I love supporting this package. My PhD work is taking up a lot of my time, but you better believe that I intend to continue to help improve this package moving forward as it is my favorite.

I think that would be a great solution! Additionally, weights are totally unnecessary to predict at the observation level (which is what is done by xlogit), so you can just avoid it entirely. However, I'm positive that you'll choose the right thing -  I see no particular benefit either way.

**Comment by arteagac** [comment]
Thank you @crforsythe! Your support with xlogit has been super helpful. Actually, I have also been quite busy with my dissertation, so I haven't had the chance to implement additional features. My hope is to have more time by the beggining of next year and I for sure will be contacting you to talk about potential enhancements for xlogit.

I have fixed this bug and I will upload the changes soon. After this, I will proceed to close this issue.

**Comment by crforsythe** [comment]
Sounds great! And good luck with your dissertation!

**Comment by arteagac** [comment]
Fixed in a0347f3.
