### ISSUE TITLE
Variation in alternatives

### ISSUE THREAD

**Issue by patrickksun** [arteagac/xlogit#16]
I am trying to use xlogit in cases where I have variation in alternatives available to each individual.  It appears that in these cases, the code will return the following error: 

"raise ValueError('inconsistent alts values in long format')"

I believe from looking at the code, this is because the "_check_long_format_consistency" function in the "_choice_model" code checks whether the total number of observations equals the product of individuals times the number of unique alternatives.   From what I can tell, this is not strictly necessary from a theoretical or a coding basis.  Could someone verify this?

Would is be possible to remove this check in the next edition of the xlogit?  In the meantime, is there some sort of workaround for this?  Thanks for any comments.

**Comment by arteagac** [comment]
Dear @patrickksun,

To conveniently reshape the data matrices and speed-up computations, xlogit expects a dataset in long format where the number of rows matches the number of unique individuals times the number of alternatives. For cases where some individuals do not make choices for all the alternatives, you can use the `avail` parameter, which models the availability of alternatives for individuals. Thus, even if the individual does not face all alternatives, xlogit requires the data rows for all the alternatives (even if they are filled with zeros) and you can use the `avail` parameter to specify the alternatives faced and not faced by individuals. Please let me know if you have further questions.

**Comment by patrickksun** [comment]
Thanks for the information.  It now works.

**Comment by arteagac** [comment]
Great! I am glad to hear that. I will proceed to close this issue.
